# Generated by Django 4.2.16 on 2025-09-09 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("movies", "0002_alter_movie_options_movie_backdrop_url_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MovieSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section_type",
                    models.CharField(
                        choices=[
                            ("basic_info", "Basic Information"),
                            ("cast_performances", "Cast & Performances"),
                            ("character_analysis", "Character Analysis"),
                            ("thematic_artistic", "Thematic & Artistic Elements"),
                            ("critical_reception", "Critical Reception & Reviews"),
                            ("legacy_impact", "Legacy & Cultural Impact"),
                        ],
                        max_length=50,
                    ),
                ),
                ("content", models.TextField()),
                ("word_count", models.IntegerField(default=0)),
                ("key_topics", models.JSONField(blank=True, default=list)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="movies.movie",
                    ),
                ),
            ],
            options={
                "ordering": ["movie", "section_type"],
                "unique_together": {("movie", "section_type")},
            },
        ),
    ]
