# Generated by Django 4.2.16 on 2025-10-07 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="moviesection",
            name="embedding",
            field=models.TextField(default=0),
        ),
    ]
