# Generated by Django 4.2.16 on 2025-10-14 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0003_alter_moviesection_embedding"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moviesection",
            name="section_type",
            field=models.CharField(
                choices=[
                    ("production", "Production & Release"),
                    ("plot_structure", "Plot & Structure"),
                    ("cast_crew", "Cast & Crew"),
                    ("characters", "Characters & Relationships"),
                    ("visual_technical", "Visual & Technical Mastery"),
                    ("themes", "Themes & Symbolism"),
                    ("reception", "Critical Reception & Analysis"),
                    ("legacy", "Cultural Impact & Legacy"),
                ],
                max_length=50,
            ),
        ),
    ]
