# Generated by Django 4.2.16 on 2025-09-09 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tmdb_id", models.IntegerField(unique=True)),
                ("title", models.CharField(max_length=255)),
                ("year", models.IntegerField()),
                ("director", models.CharField(max_length=255)),
                ("genre", models.CharField(max_length=100)),
                (
                    "imdb_rating",
                    models.DecimalField(decimal_places=1, max_digits=3, null=True),
                ),
                ("poster_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="MovieSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sectiom_type",
                    models.CharField(
                        choices=[
                            ("basic_info", "Basic Information"),
                            ("cast_performances", "Cast & Performances"),
                            ("character_analysis", "Character Analysis"),
                            ("thematic_artistic", "Thematic & Artistic Elements"),
                            ("critical_reception", "Critical Reception & Reviews"),
                            ("legacy_impact", "Legacy & Cultural Impact"),
                        ],
                        max_length=50,
                    ),
                ),
                ("word_count", models.IntegerField()),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="movies.movie",
                    ),
                ),
            ],
        ),
    ]
