# Generated by Django 4.2.16 on 2025-09-09 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="movie",
            options={"ordering": ["-year", "title"]},
        ),
        migrations.AddField(
            model_name="movie",
            name="backdrop_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="plot_summary",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="runtime",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="director",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="movie",
            name="genre",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="movie",
            name="imdb_rating",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=3, null=True
            ),
        ),
        migrations.DeleteModel(
            name="MovieSection",
        ),
    ]
